export const products = [
  {
    id: 1,
    title: "Product 1",
    price: 15,
    discount: 0,
    image: "images/product_1.jpg",
    totalAmount: 30,
    amountTaken: 0,
    colors: [
      { color: "green", isSelected: false },
      { color: "black", isSelected: false },
      { color: "white", isSelected: false },
      { color: "red", isSelected: true },
    ],
  },
  {
    id: 2,
    title: "Product 2",
    price: 30,
    discount: 5,
    image: "images/product_1.jpg",
    totalAmount: 5,
    amountTaken: 0,
    colors: [
      { color: "green", isSelected: false },
      { color: "black", isSelected: false },
      { color: "blue", isSelected: false },
      { color: "white", isSelected: true },
    ],
  },
  {
    id: 3,
    title: "Product 3",
    price: 15,
    discount: 5,
    image: "images/product_1.jpg",
    totalAmount: 15,
    amountTaken: 0,
    colors: [
      { color: "green", isSelected: false },
      { color: "black", isSelected: false },
      { color: "blue", isSelected: false },
      { color: "red", isSelected: true },
    ],
  },
  {
    id: 4,
    title: "Product 4",
    price: 30,
    discount: 10,
    image: "images/product_1.jpg",
    totalAmount: 5,
    amountTaken: 0,
    colors: [
      { color: "green", isSelected: false },
      { color: "black", isSelected: true },
      { color: "blue", isSelected: false },
      { color: "red", isSelected: false },
    ],
  },
];

export const creditCards = [
  {
    id: 1,
    type: "visa",
    number: "3453-2211-2223-3332-1111",
    bank: "Leumi",
    expiration: "05-03-2023",
    owner: "John Doe",
    selected: true,
  },
  {
    id: 2,
    type: "visa",
    number: "3453-2211-2223-3332-1111",
    bank: "Leumi",
    expiration: "05-03-2023",
    owner: "John Doe",
    selected: false,
  },
];
