export const products = [
  {
    id: 1,
    title: "Product 1",
    price: 15,
    image: "images/product_1.jpg",
    totalAmount: 30,
    amountTaken: 0,
    colors: [
      { color: "green", isSelected: false },
      { color: "black", isSelected: false },
      { color: "white", isSelected: false },
      { color: "red", isSelected: true },
    ],
  },
  {
    id: 2,
    title: "Product 2",
    price: 30,
    image: "images/product_1.jpg",
    totalAmount: 5,
    amountTaken: 0,
    colors: [
      { color: "green", isSelected: false },
      { color: "black", isSelected: false },
      { color: "blue", isSelected: false },
      { color: "white", isSelected: true },
    ],
  },
  {
    id: 3,
    title: "Product 3",
    price: 15,
    image: "images/product_1.jpg",
    totalAmount: 15,
    amountTaken: 0,
    colors: [
      { color: "green", isSelected: false },
      { color: "black", isSelected: false },
      { color: "blue", isSelected: false },
      { color: "red", isSelected: true },
    ],
  },
  {
    id: 4,
    title: "Product 4",
    price: 30,
    image: "images/product_1.jpg",
    totalAmount: 5,
    amountTaken: 0,
    colors: [
      { color: "green", isSelected: false },
      { color: "black", isSelected: true },
      { color: "blue", isSelected: false },
      { color: "red", isSelected: false },
    ],
  },
];
